#!/bin/bash
#PBS -k o
#PBS -l nodes=1:ppn=4,walltime=5:00:00

## modules
echo "Loading modules"
module unload matlab
module load matlab/2017a
module load spm/8
module unload python
module load dipy/dev
echo "Finished loading modules"

export PYTHONPATH=/N/u/brlife/git/nibabel:$PYTHONPATH

echo "copying moving and static tractograms"
moving=`jq -r '.tractogram_moving' config.json`
static=`jq -r '.tractogram_static' config.json`
subjID=`jq -r '._inputs[0].meta.subject' config.json`
cp $moving ./;
cp $static ./;
echo "Finished copying tractograms"

# Check the inputs subject id
echo "Check the inputs subject id"
stat_life_id=`jq -r '._inputs[0].meta.subject' config.json`
stat_t1_id=`jq -r '._inputs[1].meta.subject' config.json`
mov_afq_id=`jq -r '._inputs[2].meta.subject' config.json`
mov_life_id=`jq -r '._inputs[3].meta.subject' config.json`
mov_t1_id=`jq -r '._inputs[4].meta.subject' config.json`
if [ $mov_life_id == $mov_t1_id -a $mov_life_id == $mov_afq_id -a $stat_life_id == $stat_t1_id ]; then
	echo "Inputs subject IDs correctly inserted"
else
	echo "Inputs subject IDs incorrectly inserted. Check them again."
	exit 1
fi

# Build LAP environment
echo "Building LAP environment"
if [ -f "linear_assignment.c" ];then
	echo "LAP already built. Skipping"
else
	cython linear_assignment.pyx;
	python setup_lapjv.py build_ext --inplace;

	ret=$?
	if [ ! $ret -eq 0 ]; then
		echo "LAP environment build failed"
		echo $ret > finished
		exit $ret
	fi
fi

# Tractogram Input converter
echo "Input conversion to trk"
if [ -f "life_moving_output.trk" ];then
	echo "Already in proper format. Skipping conversion"
else
	matlab -nosplash -nodisplay -r "lifeConverter()";

	ret=$?
	if [ ! $ret -eq 0 ]; then
		echo "Tractogram conversion failed"
		echo $ret > finished
		exit $ret
	fi
fi

# Run LAP single example
echo "Running LAP single example"

while read tract_name; do         

    echo "Tract name: $tract_name"; 

    tract_example=$tract_name'_tract.trk' 
    output_filename=${subjID}'_'$tract_name'_tract_E'$mov_afq_id'.tck'
    array_filename='result_lap'
    superset_filename='superset_idx'
    python lap_single_example.py -moving life_moving_output.trk -static life_static_output.trk -ex $tract_example -out $output_filename;
    mv result_lap.npy ${subjID}'_'${tract_name}'_'$array_filename'_E'$mov_afq_id'.npy'
    mv superset_idx.npy ${subjID}'_'${tract_name}'_'$superset_filename'_E'$mov_afq_id'.npy'

done < tract_name_list.txt

ret=$?
if [ ! $ret -eq 0 ]; then
	echo "LAP single example failed"
	echo $ret > finished
	exit $ret
fi

echo "Complete"
